version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development
        patterns:
          - '*'
      production-dependencies:
        dependency-type: production
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    groups:
      base-images:
        patterns:
          - '*'
    ignore:
      - dependency-name: node
        update-types:
          - version-update:semver-major
