services:
  web:
    ports:
      - '${BIND_ADDRESS:-127.0.0.1}:${WEB_PORT:-3000}:3000'
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /app/apps/web/.next/cache:uid=1001,gid=1001,mode=0750

  api:
    ports:
      - '${BIND_ADDRESS:-127.0.0.1}:${API_PORT:-3001}:3001'
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp

  reporting-api:
    ports:
      - '${BIND_ADDRESS:-127.0.0.1}:${REPORTING_API_PORT:-3002}:3002'
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp

  database:
    restart: unless-stopped
