services:
  caddy:
    ports:
      - '127.0.0.1:${WEB_PORT:-3000}:80'

  web:
    environment:
      BAP_MAIL_TRANSPORT: log
      BAP_PUBLIC_ORIGIN: http://localhost:${WEB_PORT:-3000}

  database:
    ports:
      - '127.0.0.1:${POSTGRES_PORT:-5432}:5432'

networks:
  data:
    internal: false
