// The slugs a workspace may never take; the organization_slug_reserved_check migration constraint must list the same set.
export const reservedOrganizationSlugs = [
  'access',
  'api',
  'datasets',
  'design-system',
  'health',
  'invitation',
  'metrics',
  'ready',
  'sign-in',
  'sign-up',
  'forgot-password',
  'reset-password',
  'activate',
  'welcome',
  'account',
  'organizations',
  'documents',
  'members',
  'entities',
  'settings',
  'assistant',
  'audit',
  'workspaces',
  'notifications',
  'inbox',
  'employees',
  'payroll',
  'hr-settings',
  'time',
  'my-hr',
] as const;
