export const carbonThemes = ['white', 'g10', 'g90', 'g100'] as const;

export type CarbonTheme = (typeof carbonThemes)[number];

export const carbonSpacingTokens = [
  ['spacing-01', '2px'],
  ['spacing-02', '4px'],
  ['spacing-03', '8px'],
  ['spacing-04', '12px'],
  ['spacing-05', '16px'],
  ['spacing-06', '24px'],
  ['spacing-07', '32px'],
  ['spacing-08', '40px'],
  ['spacing-09', '48px'],
  ['spacing-10', '64px'],
  ['spacing-11', '80px'],
  ['spacing-12', '96px'],
  ['spacing-13', '160px'],
] as const;

export const carbonMotionTokens = [
  ['duration-fast-01', '70ms'],
  ['duration-fast-02', '110ms'],
  ['duration-moderate-01', '150ms'],
  ['duration-moderate-02', '240ms'],
  ['duration-slow-01', '400ms'],
  ['duration-slow-02', '700ms'],
  ['standard', 'productive and expressive easing'],
  ['entrance', 'productive and expressive easing'],
  ['exit', 'productive and expressive easing'],
] as const;

export const carbonColorTokenGroups = [
  'background',
  'layer',
  'field',
  'border',
  'text',
  'link',
  'icon',
  'button',
  'support',
  'focus',
  'skeleton',
  'highlight',
  'interactive',
  'toggle',
] as const;

export const carbonTypographyTokens = [
  'caption-01',
  'caption-02',
  'label-01',
  'label-02',
  'helper-text-01',
  'helper-text-02',
  'body-short-01',
  'body-short-02',
  'body-long-01',
  'body-long-02',
  'code-01',
  'code-02',
  'heading-01',
  'heading-02',
  'productive-heading-01',
  'productive-heading-02',
  'productive-heading-03',
  'productive-heading-04',
  'productive-heading-05',
  'productive-heading-06',
  'productive-heading-07',
  'expressive-paragraph-01',
  'expressive-heading-01',
  'expressive-heading-02',
  'expressive-heading-03',
  'expressive-heading-04',
  'expressive-heading-05',
  'expressive-heading-06',
  'quotation-01',
  'quotation-02',
  'display-01',
  'display-02',
  'display-03',
  'display-04',
  'legal-01',
  'legal-02',
  'body-compact-01',
  'body-compact-02',
  'heading-compact-01',
  'heading-compact-02',
  'body-01',
  'body-02',
  'heading-03',
  'heading-04',
  'heading-05',
  'heading-06',
  'heading-07',
  'fluid-heading-03',
  'fluid-heading-04',
  'fluid-heading-05',
  'fluid-heading-06',
  'fluid-paragraph-01',
  'fluid-quotation-01',
  'fluid-quotation-02',
  'fluid-display-01',
  'fluid-display-02',
  'fluid-display-03',
  'fluid-display-04',
] as const;

export const carbonComponentFamilies = [
  'AILabel',
  'AISkeleton',
  'Accordion',
  'AccordionItem',
  'ActionSet',
  'AspectRatio',
  'BadgeIndicator',
  'BigNumber',
  'Breadcrumb',
  'BreadcrumbItem',
  'Button',
  'ButtonSet',
  'Card',
  'ChatButton',
  'Checkbox',
  'CheckboxGroup',
  'ClassPrefix',
  'Coachmark',
  'CodeSnippet',
  'ComboBox',
  'ComboButton',
  'ComposedModal',
  'ContainedList',
  'ContentSwitcher',
  'ContextMenu',
  'Copy',
  'CopyButton',
  'DangerButton',
  'DataTable',
  'DataTableSkeleton',
  'DatePicker',
  'DatePickerInput',
  'Dialog',
  'Disclosure',
  'Dropdown',
  'EditInPlace',
  'ErrorBoundary',
  'ExpandableSearch',
  'FeatureFlags',
  'FileUploader',
  'FlexGrid',
  'FluidComboBox',
  'FluidDatePicker',
  'FluidDatePickerInput',
  'FluidDropdown',
  'FluidForm',
  'FluidMultiSelect',
  'FluidNumberInput',
  'FluidSearch',
  'FluidSelect',
  'FluidTextArea',
  'FluidTextInput',
  'FluidTimePicker',
  'FluidTimePickerSelect',
  'Form',
  'FormGroup',
  'FormItem',
  'FormLabel',
  'FullPageError',
  'Grid',
  'Heading',
  'HideAtBreakpoint',
  'Icon',
  'IconButton',
  'IconIndicator',
  'Icons',
  'IdPrefix',
  'InlineCheckbox',
  'InlineLoading',
  'InterstitialScreen',
  'Layer',
  'Layout',
  'LayoutDirection',
  'Link',
  'ListBox',
  'ListItem',
  'Loading',
  'Menu',
  'MenuButton',
  'Modal',
  'ModalWrapper',
  'MultiSelect',
  'Notification',
  'NumberInput',
  'OptionsTile',
  'OrderedList',
  'OverflowHandler',
  'OverflowMenu',
  'OverflowMenuItem',
  'OverflowMenuV2',
  'PageHeader',
  'Pagination',
  'PaginationNav',
  'PasswordInput',
  'Plex',
  'Popover',
  'Portal',
  'PrimaryButton',
  'ProgressBar',
  'ProgressIndicator',
  'RadioButton',
  'RadioButtonGroup',
  'RadioTile',
  'Resizer',
  'ScrollGradient',
  'Search',
  'SecondaryButton',
  'Select',
  'SelectItem',
  'SelectItemGroup',
  'ShapeIndicator',
  'SidePanel',
  'SkeletonIcon',
  'SkeletonPlaceholder',
  'SkeletonText',
  'Slider',
  'Stack',
  'StructuredList',
  'Switch',
  'Tab',
  'TabContent',
  'Tabs',
  'Tag',
  'Text',
  'TextArea',
  'TextInput',
  'Theme',
  'Tile',
  'TileGroup',
  'TimePicker',
  'TimePickerSelect',
  'Toggle',
  'ToggleSmall',
  'Toggletip',
  'Tooltip',
  'TreeView',
  'TruncatedText',
  'UIShell',
  'UnorderedList',
  'UserAvatar',
] as const;

export const carbonChartComponents = [
  'AreaChart',
  'StackedAreaChart',
  'GroupedBarChart',
  'SimpleBarChart',
  'StackedBarChart',
  'BoxplotChart',
  'BubbleChart',
  'BulletChart',
  'ChoroplethChart',
  'DonutChart',
  'GaugeChart',
  'HistogramChart',
  'LineChart',
  'LollipopChart',
  'PieChart',
  'ScatterChart',
  'MeterChart',
  'RadarChart',
  'ComboChart',
  'TreeChart',
  'TreemapChart',
  'CirclePackChart',
  'WordCloudChart',
  'AlluvialChart',
  'HeatmapChart',
] as const;

export const carbonChartExperimentalComponents = [
  'ExperimentalChoroplethChart',
] as const;

export const carbonChartDiagramPrimitives = [
  'ArrowLeftMarker',
  'ArrowRightMarker',
  'CardNode',
  'CardNodeColumn',
  'CardNodeLabel',
  'CardNodeSubtitle',
  'CardNodeTitle',
  'CircleMarker',
  'DiamondMarker',
  'Edge',
  'Marker',
  'ShapeNode',
  'SquareMarker',
  'TeeMarker',
] as const;

export const carbonPatterns = [
  'Common actions',
  'Dialogs',
  'Disabled states',
  'Disclosures',
  'Empty states',
  'Filtering',
  'Forms',
  'Global header',
  'Loading',
  'Login',
  'Notifications',
  'Read-only inputs',
  'Search',
  'Text toolbar',
] as const;
